# Changes here will be overwritten by Copier
_commit: v0.3.1
_src_path: gh:LSSTDESC/RAIL-project-template
author_email: later@later.com
author_name: LSST Dark Energy Science Collaboration (DESC)
create_example_module: false
package_name: hub
project_name: pz-rail
