base_config:
  trainfile: /global/cfs/cdirs/lsst/groups/WL/users/zuntz/tomo_challenge_data/ugrizy/mini_training.hdf5
  testfile: /global/cfs/cdirs/lsst/groups/WL/users/zuntz/tomo_challenge_data/ugrizy/mini_validation.hdf5
  configpath: ./configs
  outpath: ./results