run_params:
  class_name: delightPZ
  run_name: test_delightPZ
  rand_width: 0.025
  rand_zmin: 0.0
  rand_zmax: 3.0
  nzbins: 301
  dlght_width: 0.025
  dlght_zmin: 0.0
  dlght_zmax: 3.0
  tempdir: "./tmp"
  tempdatadir: "./tmp/delight_data"
  delightparamfile: "parametersTest.cfg"
  dlght_tutorialmode: True


