runs:
  run1:
    run_params:
      class_name: randomPZ
      outfile_tag: test1
      rand_width: 0.025
      rand_zmin: 0.0
      rand_zmax: 3.0
      nzbins: 301
  run2:
    run_params:
      class_name: randomPZ
      outfile_tag: test2
      rand_width: 0.01
      rand_zmin: 0.0
      rand_zmax: 3.0
      nzbins: 301
